import colors from 'config/sharedStyles/colors';

export default {
  colors: {...colors},

  backgroundColor: {
    yellow: {backgroundColor: colors.yellow},
    green: {backgroundColor: colors.green},
    red: {backgroundColor: colors.red},
    pink: {backgroundColor: colors.pink},
    blue: {backgroundColor: colors.blue},
    seaBlue: {backgroundColor: colors.seaBlue},
    dark: {backgroundColor: colors.dark},
    lightBlue: {backgroundColor: colors.lightBlue},
    softBlue: {backgroundColor: colors.softBlue},
    darkBlue: {backgroundColor: colors.darkBlue},
    white: {backgroundColor: colors.white},
    lightWhite: {backgroundColor: colors.lightWhite},
    lightGrey: {backgroundColor: colors.lightGrey},
    softGrey: {backgroundColor: colors.softGrey},
  },
  tintColor: {
    yellow: {tintColor: colors.yellow},
    green: {tintColor: colors.green},
    red: {tintColor: colors.red},
    pink: {tintColor: colors.pink},
    blue: {tintColor: colors.blue},
    seaBlue: {tintColor: colors.seaBlue},
    dark: {tintColor: colors.dark},
    lightBlue: {tintColor: colors.lightBlue},
    softBlue: {tintColor: colors.softBlue},
    darkBlue: {tintColor: colors.darkBlue},
    white: {tintColor: colors.white},
    lightWhite: {tintColor: colors.lightWhite},
    lightGrey: {tintColor: colors.lightGrey},
    softGrey: {tintColor: colors.softGrey},
  },
  color: {
    yellow: {color: colors.yellow},
    green: {color: colors.green},
    red: {color: colors.red},
    pink: {color: colors.pink},
    blue: {color: colors.blue},
    seaBlue: {color: colors.seaBlue},
    dark: {color: colors.dark},
    lightBlue: {color: colors.lightBlue},
    softBlue: {color: colors.softBlue},
    darkBlue: {color: colors.darkBlue},
    white: {color: colors.white},
    lightWhite: {color: colors.lightWhite},
    lightGrey: {color: colors.lightGrey},
    softGrey: {color: colors.softGrey},
  },
  borderColor: {
    yellow: {borderColor: colors.yellow},
    green: {borderColor: colors.green},
    red: {borderColor: colors.red},
    pink: {borderColor: colors.pink},
    blue: {borderColor: colors.blue},
    seaBlue: {borderColor: colors.seaBlue},
    dark: {borderColor: colors.dark},
    lightBlue: {borderColor: colors.lightBlue},
    softBlue: {borderColor: colors.softBlue},
    darkBlue: {borderColor: colors.darkBlue},
    white: {borderColor: colors.white},
    lightWhite: {borderColor: colors.lightWhite},
    lightGrey: {borderColor: colors.lightGrey},
    softGrey: {borderColor: colors.softGrey},
  },
};
